### ISSUE TITLE
Bug: cannot retrieve version information for pom outside work directory

### ISSUE THREAD

**Issue by mattdibi** [JActions/maven-version#1]
Hi there,
as per title we found an issue with this action when used with a repo with a `pom.xml` outside the work directory.
It reports:
```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/runner/work/repo/repo). Please verify you invoked Maven from the correct directory. -> [Help 1]
```

even though the `pom.xml` path was specified.

There seems to be a bug in the action sources as the `pom.xml` path [is set](https://github.com/JActions/maven-version/blob/497a8ea3a19d17d429f34fefe7ad432dd05c48d4/action.yaml#L9) but [not used.](https://github.com/JActions/maven-version/blob/497a8ea3a19d17d429f34fefe7ad432dd05c48d4/action.yaml#L24).

I think the proper fix would be something like:

```yaml
runs:
  using: composite
  steps:
    - id: resolve-version
      shell: bash
      run: "echo \"::set-output name=resolved-version::\
        $(mvn -Dexec.executable=echo -Dexec.args='${project.version}' -f ${{inputs.pom}} --non-recursive exec:exec --quiet)\""
```
